# Generated by Django 4.0.5 on 2022-06-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub',
        ),
        migrations.AlterField(
            model_name='cart',
            name='members',
            field=models.ManyToManyField(related_name='cart_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='WorkSpace',
        ),
        migrations.AddField(
            model_name='lists',
            name='cards',
            field=models.ManyToManyField(to='todo.cart'),
        ),
        migrations.AddField(
            model_name='boards',
            name='lists',
            field=models.ManyToManyField(related_name='boards_list', to='todo.lists'),
        ),
    ]
