# Generated by Django 4.0.5 on 2022-06-10 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_boards_lists_remove_workspace_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(related_name='board_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
