# Generated by Django 4.0.5 on 2022-06-10 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_boards_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='boards_list', to='todo.lists'),
        ),
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='cart_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
