# Generated by Django 4.0.5 on 2022-06-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_boards_lists_alter_boards_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='cards',
        ),
        migrations.AddField(
            model_name='cart',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.lists'),
        ),
        migrations.AddField(
            model_name='lists',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_board', to='todo.boards'),
        ),
    ]
