# Generated by Django 4.0.5 on 2022-06-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_boards_lists_remove_lists_cards_cart_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_list', to='todo.lists'),
        ),
    ]
