# Generated by Django 4.0.5 on 2022-06-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_cart_desc_alter_cart_end_time_alter_cart_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='desc',
            field=models.TextField(default='Add a more detailed description... '),
        ),
    ]
