# Generated by Django 4.0.5 on 2022-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_cart_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
