# Generated by Django 4.0.5 on 2022-06-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Social', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.cart', verbose_name='cart'),
        ),
    ]
