# Generated by Django 4.0.5 on 2022-06-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_cart_desc_alter_cart_end_time_alter_cart_list'),
        ('Social', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cards',
        ),
        migrations.AddField(
            model_name='comment',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.cart', verbose_name='cards'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
