# Generated by Django 4.0.5 on 2022-06-06 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_mobile_verified_alter_otp_exp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_mobile_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='exp_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 17, 14, 2, 595842, tzinfo=utc), verbose_name='exp_time'),
        ),
    ]
